### ISSUE TITLE
`Table`中`badge`会显示在固定列上面

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#1478]
参考：
某一列固定在左侧，右侧有一列内容中有`badge`，表格发生滚动，`badge`列会显示在固定列上面。

应该是固定列`z-index`层级不够，
```less
.arco-table-col-fixed-left, .arco-table-col-fixed-right{
    z-index: 1 ; // 1可能不够
}
```
