### ISSUE TITLE
滚动条的样式是否都能调整成Sider那样的呢

### ISSUE THREAD

**Issue by hiipeng** [arco-design/arco-design-vue#1563]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
Sider的滚动条做的就非常棒

## What problem does this feature solve?
现在的滚动条在黑暗主题下显得特别不协调，在亮色主题下显得也不是很美观。特别希望都能像Sider的滚动条一样，既美观又有整体感。
![image](https://user-images.githubusercontent.com/32444545/186593257-8cb40c9f-d361-4156-92dc-097c96a92cd4.png)
![image](https://user-images.githubusercontent.com/32444545/186593302-d4b12f79-8ef7-4220-bd5c-90d172a55915.png)
![image](https://user-images.githubusercontent.com/32444545/186596956-8e047b99-9793-4640-a3b1-765b309f1966.png)

**Comment by hiipeng** [comment]
<img width="1845" alt="image" src="https://user-images.githubusercontent.com/32444545/188650253-55ee8d51-31f0-4f7a-aaae-6086535a5ad2.png">
OK ↑
<img width="1851" alt="image" src="https://user-images.githubusercontent.com/32444545/188650509-7fa7dc1a-6b1a-47fc-a08e-28e28c1bb3f6.png">
OK ↑
<img width="1285" alt="image" src="https://user-images.githubusercontent.com/32444545/188651183-02c632eb-4d80-4941-b263-062a449f3e30.png">
OK ↑
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/32444545/188651010-fd001be1-07ad-4f2b-b746-345f43b24a44.png">
当出现滚动条出现后，鼠标移出或已入，样式还会变成没改之前的。亮色模式也有这个问题。↑

**Comment by hehehai** [comment]
@hiipeng hi，这里菜单栏使用的是自定义滚动条，而组件目前都是系统滚动条（自定义滚动目前在 [beta](https://github.com/arco-design/arco-design-vue/tree/beta)）很快会发布的。或者你可以自己设置滚动条的样式

```css
.box {
	&::-webkit-scrollbar {
      display: none;
      width: 10px;
      background: transparent;
    }

    &::-webkit-scrollbar-thumb {
      background: var(--color-fill-3) content-box;
      border: 2px solid transparent;
      border-radius: 5px;

      &:hover {
        background-color: var(--color-fill-4);
      }
    }
}
```
