### ISSUE TITLE
关于颜色变量值的疑问

### ISSUE THREAD

**Issue by leecz** [arco-design/arco-design-vue#1876]
当前 '@arco-design/web-vue/dist/arco.css' ，颜色变量是这样的：

```css
  --arcoblue-6: 22,93,255;
```
使用时是这样的：

```css
.arco-menu-light .arco-menu-inline-header.arco-menu-selected {
  color: rgb(var(--primary-6));
}
```

这种方式会产生一个问题，当要覆盖原有的颜色时（不使用主题定制，直接css覆盖），会稍微有点麻烦，比如：

```css
/*没法直接使用颜色定义*/
--primary-6: #165dfa;
 --primary-6: rgb(22,93,250); 

/*只能是下面这种方式，有点不太直观*/
 --primary-6: 22,93,250; 
```

为什么颜色变量是现在的方式定义，而不直接使用完整的颜色值定义？

```css
--arcoblue-6: rgb(22,93,255);
```
