### ISSUE TITLE
tree组件的额外节点需要改进用户体验

### ISSUE THREAD

**Issue by sx1989827** [arco-design/arco-design-vue#2491]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
可道云的文件管理树形菜单就是这么设计的

## What problem does this feature solve?
当前tree组件通过extra slot添加节点的菜单，但是这样的话所有的节点都会同时显示extra slot的内容，很不美观，期望当鼠标移动到节点那一行的时候显示那一行的extra内容，移走就隐藏，这样界面会美观很多

**Comment by kaikaibenkai** [comment]
自行解决

```vue
<template #extra>
  <div class='show-when-hover'>
    ..
  </div>
</template>
```

```css
.show-when-hover {
  display: none;
}
.show-when-hover:hover {
  display: block;
}
```
