### ISSUE TITLE
Layout组件在黑暗模式下样式不正确

### ISSUE THREAD

**Issue by Kigoal** [arco-design/arco-design-vue#254]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-vue: 2.6.1
- **系统版本:** MacOS 12.0.1
- **浏览器版本:** Edge 95
- **复现地址:** https://arco.design/

## 预期结果
`Layout.Sider` 的css改为 `arco-layout-sider-dark` 或更改 `box-shadow` 的颜色值

## 复现步骤

此时 `Layout.Sider` 的css还是 `arco-layout-sider-light` 

```css
.arco-layout-sider-light {
    background: var(--color-menu-light-bg);
    box-shadow: 0 2px 5px 0 rgb(0 0 0 / 8%);
}
```

![image](https://user-images.githubusercontent.com/21240282/143396453-50241156-4874-4acb-92c0-d92bf32a8f8f.png)
