### ISSUE TITLE
avatar-group popover里头像z-index可能为负数

### ISSUE THREAD

**Issue by kairyou** [arco-design/arco-design-vue#2745]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.52.1
- **Framework version:** 3.2.47
- **Browser:** chrome118.0.0.0
- **Reproduction Link:** https://stackblitz.com/edit/zubk3f?file=src%2FApp.vue

## Extra info
popover里的z-index 从 max-count 开始递减, zindex 可能出现负数(只要剩余的数量大于max-count), 导致部分看不见.

```scss
// 全局加上这个样式, 可以临时解决
.arco-popover-popup-content {
  position: relative;
  z-index: 1;
}
```
