### ISSUE TITLE
新增加的color picker 打包 less 报错

### ISSUE THREAD

**Issue by febelery** [arco-design/arco-design-vue#3038]
```shell

[vite:css] [less] variable @input-size-mini-height is undefined
file: /home/xxx/node_modules/@arco-design/web-vue/es/color-picker/style/index.less:17:5
error during build:
Error: [less] variable @input-size-mini-height is undefined
    at less (file:///home/xxx/node_modules/vite/dist/node/chunks/dep-f11f7337.js:44722:33)
    at async compileCSS (file:///home/xxx/node_modules/vite/dist/node/chunks/dep-f11f7337.js:44125:34)
    at async Object.transform (file:///home/xxx/node_modules/vite/dist/node/chunks/dep-f11f7337.js:43693:55)
    at async transform (file:///home/xxx/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21734:16)
    at async ModuleLoader.addModuleSource (file:///home/xxx/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:21959:30)
```

## Basic Info 
- **Package Name And Version:** @arco-design/web-vue@2.55.0
- **Framework version:** Vue 3.2
- **Browser:** chrome122.0.0.0

**Comment by febelery** [comment]
手动在` node_modules/@arco-design/web-vue/es/color-picker/style/index.less` 文件添加如下代码可正常打包
```less
@import './token.less';

@color-picker-prefix-cls: ~'@{prefix}-color-picker';
@input-size-mini-height: 16px;
@input-size-small-height: 16px;
@input-size-medium-height: 16px;
@input-size-large-height: 16px;
```

其中
```less
@input-size-mini-height: 16px;
@input-size-small-height: 16px;
@input-size-medium-height: 16px;
@input-size-large-height: 16px;
```
是手动添加的部分
