### ISSUE TITLE
space纵向时item宽度不为100%

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#328]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## What are the similar cases of this feature
类似elementplus的space

## What problem does this feature solve?
纵向时，item的宽度不是100%，希望可以提供类似`fill`属性就行控制

**Comment by llk2yq** [comment]
2.10.1版本还没有

**Comment by llk2yq** [comment]
先这样用着先：
```scss
.arco-space-vertical {
    width: 100%;
    .arco-space-item {
        width: 100%;
    }
}
```
