### ISSUE TITLE
暗黑模式模式无法支持为默认选项，必须手动设置

### ISSUE THREAD

**Issue by fish-uncle** [arco-design/arco-design-vue#33]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-vue/issues)

## Basic Info
- **依赖包名 及 版本:** @arco-design/web-vue:2.0.2
- **系统版本:** iMac (Retina 5K, 27-inch, 2017)
- **浏览器版本:** chrome  94.0.4606.81

## 预期结果
```
<body arco-theme="dark">
// 或者
app.use(ArcoVue, {
	arcoTheme: 'drak',
})
```

## 复现步骤
```
<body arco-theme="dark"> // 无法达到暗黑模式
```
必须手动设置
```
document.body.setAttribute('arco-theme', 'dark')
```

**Comment by LuckyHookin** [comment]
https://stackblitz.com/edit/vue-r1qnlm?file=public%2Findex.html
没毛病呀，暗黑模式样式都是 css 选择器管的，类似这样：
``` css
// dark mode
@{arco-theme-tag}[arco-theme='dark'] {
  ...
}

// arco-design/arco-design-vue/packages/web-vue/components/style/theme/global.less
@arco-theme-tag: body; // css 变量定义的选择器

```
你是不是打错单词了？
