### ISSUE TITLE
为什么 `font-family` 里会自动添加 `Inter` 字体？

### ISSUE THREAD

**Issue by zndle** [arco-design/arco-design-vue#3358]
如果我在 `Vite` 配置文件里，修改样式变量 `font-family` ，会自动加上一个叫 `Inter` 的字体。

```ts
css: {
      preprocessorOptions: {
        less: {
          modifiVars: {
            'font-family':
              '-apple-system, BlinkMacSystemFont, "Helvetica Neue", "PingFang SC", "Microsoft YaHei", "Source Han Sans SC", "Noto Sans CJK SC", "WenQuanYi Micro Hei", sans-serif;',
          },
          javascriptEnabled: true,
        },
      },
    },
```

最终得到的 css , body.font-family 会自动加上 `Inter` .

看了下官网，也是加了 `Inter`, 
```css
html, body {
    line-height: 1.5;
    -webkit-text-size-adjust: 100%;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-family: Inter, -apple-system, BlinkMacSystemFont, PingFang SC, Hiragino Sans GB, noto sans, Microsoft YaHei, Helvetica Neue, Helvetica, Arial, sans-serif;
}
```
已经换机器，换浏览器试过了。请问是怎么回事？
