### ISSUE TITLE
Table 样式问题

### ISSUE THREAD

**Issue by Menusyes** [arco-design/arco-design-vue#3362]
Table中，td在选中状态下背景色是`--color-fill-1`，
```css
.arco-table-tr-checked .arco-table-td {
    background-color: var(--color-fill-1);
}
```
而`--color-fill-1`在深色模式下是`rgba(255, 255, 255, .04)`，
![image](https://github.com/user-attachments/assets/9935c765-308a-48c9-af84-cf1b1b4c06ed)
所以在 深色模式+选中状态时，存在固定列且滚动时，会出现以下情况：
![image](https://github.com/user-attachments/assets/d2adde01-361a-4019-8cea-95244159e74f)
