### ISSUE TITLE
让 normalize css 成为可选项

### ISSUE THREAD

**Issue by Arman19941113** [arco-design/arco-design-vue#3512]
## 问题
TailwindCSS4 使用了 CSS layer，normalize css 修改了一些标签的样式
```css
button,
input,
optgroup,
select,
textarea {
  margin: 0; /* 2 */
  font-size: 100%; /* 1 */
  font-family: inherit; /* 1 */
  line-height: 1.15; /* 1 */
}
```
这导致 utility css 始终被 arco-design-vue 的基础样式覆盖，无法在 button 等标签上使用 mt 等工具类。

## 建议
让 normalize css 成为可选配置，或者支持在 CSS base layer 引入 normalize 样式。
