### ISSUE TITLE
[讨论] Spin的css属性疑问

### ISSUE THREAD

**Issue by llk2yq** [arco-design/arco-design-vue#897]
注意到：
```css
.arco-spin {
    display: inline-block;
}
```
出于什么考虑给spin设置了`display`属性？
[文档中的例子](https://arco.design/vue/component/spin#tip)，由于设置了该属性，导致没有居中，所以个人觉得可以去掉该属性。
